### ISSUE TITLE
README.md

### ISSUE THREAD

**Issue by pdinger** [RosenkoetterM/MalisAufgabe#2]
Hey Martha,

zunächst mal was formales. Wenn ich das richtig sehe hast du kein "echtes" Readme, dass Infos über dein konkretes Projekt bzw. Aufgabenstellung gibt. Deine Datei heißt zwar Readme, ist aber eher schon ein inhaltliches Dokument. 

Vorschlag:
1. Umbennenung: du kannst die verwendete Datei gerne umbennen
2. README: du könntest ein echtes Readme schreiben, dass einfach kurz sagt was du mit dem repository machst (Aufgabenstellung)

LG aus dem Zug

**Comment by RosenkoetterM** [comment]
habe die Datei umbenannt
